<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Country;
use App\Models\State;
use Illuminate\Database\Seeder;

/**
 * Seeds first-level administrative divisions (states/provinces) for a
 * curated set of major countries — not all 196 countries in the countries
 * table, since many have no meaningful "state" tier and a fully accurate
 * ISO 3166-2 seed for every country would be thousands of rows of
 * uncertain accuracy. Extend self::STATES_BY_ISO2 to add more countries.
 *
 * Each row: [name, code, iso_code suffix, capital].
 */
class StateSeeder extends Seeder
{
    private const STATES_BY_ISO2 = [
        'IN' => [
            ['Andhra Pradesh', 'AP', 'IN-AP', 'Amaravati'],
            ['Arunachal Pradesh', 'AR', 'IN-AR', 'Itanagar'],
            ['Assam', 'AS', 'IN-AS', 'Dispur'],
            ['Bihar', 'BR', 'IN-BR', 'Patna'],
            ['Chhattisgarh', 'CG', 'IN-CT', 'Raipur'],
            ['Goa', 'GA', 'IN-GA', 'Panaji'],
            ['Gujarat', 'GJ', 'IN-GJ', 'Gandhinagar'],
            ['Haryana', 'HR', 'IN-HR', 'Chandigarh'],
            ['Himachal Pradesh', 'HP', 'IN-HP', 'Shimla'],
            ['Jharkhand', 'JH', 'IN-JH', 'Ranchi'],
            ['Karnataka', 'KA', 'IN-KA', 'Bengaluru'],
            ['Kerala', 'KL', 'IN-KL', 'Thiruvananthapuram'],
            ['Madhya Pradesh', 'MP', 'IN-MP', 'Bhopal'],
            ['Maharashtra', 'MH', 'IN-MH', 'Mumbai'],
            ['Manipur', 'MN', 'IN-MN', 'Imphal'],
            ['Meghalaya', 'ML', 'IN-ML', 'Shillong'],
            ['Mizoram', 'MZ', 'IN-MZ', 'Aizawl'],
            ['Nagaland', 'NL', 'IN-NL', 'Kohima'],
            ['Odisha', 'OD', 'IN-OR', 'Bhubaneswar'],
            ['Punjab', 'PB', 'IN-PB', 'Chandigarh'],
            ['Rajasthan', 'RJ', 'IN-RJ', 'Jaipur'],
            ['Sikkim', 'SK', 'IN-SK', 'Gangtok'],
            ['Tamil Nadu', 'TN', 'IN-TN', 'Chennai'],
            ['Telangana', 'TG', 'IN-TG', 'Hyderabad'],
            ['Tripura', 'TR', 'IN-TR', 'Agartala'],
            ['Uttar Pradesh', 'UP', 'IN-UP', 'Lucknow'],
            ['Uttarakhand', 'UK', 'IN-UT', 'Dehradun'],
            ['West Bengal', 'WB', 'IN-WB', 'Kolkata'],
            ['Andaman and Nicobar Islands', 'AN', 'IN-AN', 'Port Blair'],
            ['Chandigarh', 'CH', 'IN-CH', 'Chandigarh'],
            ['Dadra and Nagar Haveli and Daman and Diu', 'DN', 'IN-DH', 'Daman'],
            ['Delhi', 'DL', 'IN-DL', 'New Delhi'],
            ['Jammu and Kashmir', 'JK', 'IN-JK', 'Srinagar'],
            ['Ladakh', 'LA', 'IN-LA', 'Leh'],
            ['Lakshadweep', 'LD', 'IN-LD', 'Kavaratti'],
            ['Puducherry', 'PY', 'IN-PY', 'Puducherry'],
        ],
        'US' => [
            ['Alabama', 'AL', 'US-AL', 'Montgomery'],
            ['Alaska', 'AK', 'US-AK', 'Juneau'],
            ['Arizona', 'AZ', 'US-AZ', 'Phoenix'],
            ['Arkansas', 'AR', 'US-AR', 'Little Rock'],
            ['California', 'CA', 'US-CA', 'Sacramento'],
            ['Colorado', 'CO', 'US-CO', 'Denver'],
            ['Connecticut', 'CT', 'US-CT', 'Hartford'],
            ['Delaware', 'DE', 'US-DE', 'Dover'],
            ['Florida', 'FL', 'US-FL', 'Tallahassee'],
            ['Georgia', 'GA', 'US-GA', 'Atlanta'],
            ['Hawaii', 'HI', 'US-HI', 'Honolulu'],
            ['Idaho', 'ID', 'US-ID', 'Boise'],
            ['Illinois', 'IL', 'US-IL', 'Springfield'],
            ['Indiana', 'IN', 'US-IN', 'Indianapolis'],
            ['Iowa', 'IA', 'US-IA', 'Des Moines'],
            ['Kansas', 'KS', 'US-KS', 'Topeka'],
            ['Kentucky', 'KY', 'US-KY', 'Frankfort'],
            ['Louisiana', 'LA', 'US-LA', 'Baton Rouge'],
            ['Maine', 'ME', 'US-ME', 'Augusta'],
            ['Maryland', 'MD', 'US-MD', 'Annapolis'],
            ['Massachusetts', 'MA', 'US-MA', 'Boston'],
            ['Michigan', 'MI', 'US-MI', 'Lansing'],
            ['Minnesota', 'MN', 'US-MN', 'Saint Paul'],
            ['Mississippi', 'MS', 'US-MS', 'Jackson'],
            ['Missouri', 'MO', 'US-MO', 'Jefferson City'],
            ['Montana', 'MT', 'US-MT', 'Helena'],
            ['Nebraska', 'NE', 'US-NE', 'Lincoln'],
            ['Nevada', 'NV', 'US-NV', 'Carson City'],
            ['New Hampshire', 'NH', 'US-NH', 'Concord'],
            ['New Jersey', 'NJ', 'US-NJ', 'Trenton'],
            ['New Mexico', 'NM', 'US-NM', 'Santa Fe'],
            ['New York', 'NY', 'US-NY', 'Albany'],
            ['North Carolina', 'NC', 'US-NC', 'Raleigh'],
            ['North Dakota', 'ND', 'US-ND', 'Bismarck'],
            ['Ohio', 'OH', 'US-OH', 'Columbus'],
            ['Oklahoma', 'OK', 'US-OK', 'Oklahoma City'],
            ['Oregon', 'OR', 'US-OR', 'Salem'],
            ['Pennsylvania', 'PA', 'US-PA', 'Harrisburg'],
            ['Rhode Island', 'RI', 'US-RI', 'Providence'],
            ['South Carolina', 'SC', 'US-SC', 'Columbia'],
            ['South Dakota', 'SD', 'US-SD', 'Pierre'],
            ['Tennessee', 'TN', 'US-TN', 'Nashville'],
            ['Texas', 'TX', 'US-TX', 'Austin'],
            ['Utah', 'UT', 'US-UT', 'Salt Lake City'],
            ['Vermont', 'VT', 'US-VT', 'Montpelier'],
            ['Virginia', 'VA', 'US-VA', 'Richmond'],
            ['Washington', 'WA', 'US-WA', 'Olympia'],
            ['West Virginia', 'WV', 'US-WV', 'Charleston'],
            ['Wisconsin', 'WI', 'US-WI', 'Madison'],
            ['Wyoming', 'WY', 'US-WY', 'Cheyenne'],
            ['District of Columbia', 'DC', 'US-DC', 'Washington'],
        ],
        'CA' => [
            ['Alberta', 'AB', 'CA-AB', 'Edmonton'],
            ['British Columbia', 'BC', 'CA-BC', 'Victoria'],
            ['Manitoba', 'MB', 'CA-MB', 'Winnipeg'],
            ['New Brunswick', 'NB', 'CA-NB', 'Fredericton'],
            ['Newfoundland and Labrador', 'NL', 'CA-NL', "St. John's"],
            ['Nova Scotia', 'NS', 'CA-NS', 'Halifax'],
            ['Ontario', 'ON', 'CA-ON', 'Toronto'],
            ['Prince Edward Island', 'PE', 'CA-PE', 'Charlottetown'],
            ['Quebec', 'QC', 'CA-QC', 'Quebec City'],
            ['Saskatchewan', 'SK', 'CA-SK', 'Regina'],
            ['Northwest Territories', 'NT', 'CA-NT', 'Yellowknife'],
            ['Nunavut', 'NU', 'CA-NU', 'Iqaluit'],
            ['Yukon', 'YT', 'CA-YT', 'Whitehorse'],
        ],
        'AU' => [
            ['New South Wales', 'NSW', 'AU-NSW', 'Sydney'],
            ['Queensland', 'QLD', 'AU-QLD', 'Brisbane'],
            ['South Australia', 'SA', 'AU-SA', 'Adelaide'],
            ['Tasmania', 'TAS', 'AU-TAS', 'Hobart'],
            ['Victoria', 'VIC', 'AU-VIC', 'Melbourne'],
            ['Western Australia', 'WA', 'AU-WA', 'Perth'],
            ['Australian Capital Territory', 'ACT', 'AU-ACT', 'Canberra'],
            ['Northern Territory', 'NT', 'AU-NT', 'Darwin'],
        ],
        'GB' => [
            ['England', 'ENG', 'GB-ENG', 'London'],
            ['Scotland', 'SCT', 'GB-SCT', 'Edinburgh'],
            ['Wales', 'WLS', 'GB-WLS', 'Cardiff'],
            ['Northern Ireland', 'NIR', 'GB-NIR', 'Belfast'],
        ],
        'DE' => [
            ['Baden-Württemberg', 'BW', 'DE-BW', 'Stuttgart'],
            ['Bavaria', 'BY', 'DE-BY', 'Munich'],
            ['Berlin', 'BE', 'DE-BE', 'Berlin'],
            ['Brandenburg', 'BB', 'DE-BB', 'Potsdam'],
            ['Bremen', 'HB', 'DE-HB', 'Bremen'],
            ['Hamburg', 'HH', 'DE-HH', 'Hamburg'],
            ['Hesse', 'HE', 'DE-HE', 'Wiesbaden'],
            ['Lower Saxony', 'NI', 'DE-NI', 'Hanover'],
            ['Mecklenburg-Vorpommern', 'MV', 'DE-MV', 'Schwerin'],
            ['North Rhine-Westphalia', 'NW', 'DE-NW', 'Düsseldorf'],
            ['Rhineland-Palatinate', 'RP', 'DE-RP', 'Mainz'],
            ['Saarland', 'SL', 'DE-SL', 'Saarbrücken'],
            ['Saxony', 'SN', 'DE-SN', 'Dresden'],
            ['Saxony-Anhalt', 'ST', 'DE-ST', 'Magdeburg'],
            ['Schleswig-Holstein', 'SH', 'DE-SH', 'Kiel'],
            ['Thuringia', 'TH', 'DE-TH', 'Erfurt'],
        ],
        'FR' => [
            ['Auvergne-Rhône-Alpes', 'ARA', 'FR-ARA', 'Lyon'],
            ['Bourgogne-Franche-Comté', 'BFC', 'FR-BFC', 'Dijon'],
            ['Brittany', 'BRE', 'FR-BRE', 'Rennes'],
            ['Centre-Val de Loire', 'CVL', 'FR-CVL', 'Orléans'],
            ['Corsica', 'COR', 'FR-COR', 'Ajaccio'],
            ['Grand Est', 'GES', 'FR-GES', 'Strasbourg'],
            ['Hauts-de-France', 'HDF', 'FR-HDF', 'Lille'],
            ['Île-de-France', 'IDF', 'FR-IDF', 'Paris'],
            ['Normandy', 'NOR', 'FR-NOR', 'Rouen'],
            ['Nouvelle-Aquitaine', 'NAQ', 'FR-NAQ', 'Bordeaux'],
            ['Occitanie', 'OCC', 'FR-OCC', 'Toulouse'],
            ['Pays de la Loire', 'PDL', 'FR-PDL', 'Nantes'],
            ["Provence-Alpes-Côte d'Azur", 'PAC', 'FR-PAC', 'Marseille'],
        ],
        'IT' => [
            ['Abruzzo', 'ABR', 'IT-65', "L'Aquila"],
            ['Aosta Valley', 'AOS', 'IT-23', 'Aosta'],
            ['Apulia', 'PUG', 'IT-75', 'Bari'],
            ['Basilicata', 'BAS', 'IT-77', 'Potenza'],
            ['Calabria', 'CAL', 'IT-78', 'Catanzaro'],
            ['Campania', 'CAM', 'IT-72', 'Naples'],
            ['Emilia-Romagna', 'EMR', 'IT-45', 'Bologna'],
            ['Friuli-Venezia Giulia', 'FVG', 'IT-36', 'Trieste'],
            ['Lazio', 'LAZ', 'IT-62', 'Rome'],
            ['Liguria', 'LIG', 'IT-42', 'Genoa'],
            ['Lombardy', 'LOM', 'IT-25', 'Milan'],
            ['Marche', 'MAR', 'IT-57', 'Ancona'],
            ['Molise', 'MOL', 'IT-67', 'Campobasso'],
            ['Piedmont', 'PIE', 'IT-21', 'Turin'],
            ['Sardinia', 'SAR', 'IT-88', 'Cagliari'],
            ['Sicily', 'SIC', 'IT-82', 'Palermo'],
            ['Trentino-Alto Adige', 'TAA', 'IT-32', 'Trento'],
            ['Tuscany', 'TOS', 'IT-52', 'Florence'],
            ['Umbria', 'UMB', 'IT-55', 'Perugia'],
            ['Veneto', 'VEN', 'IT-34', 'Venice'],
        ],
        'ES' => [
            ['Andalusia', 'AN', 'ES-AN', 'Seville'],
            ['Aragon', 'AR', 'ES-AR', 'Zaragoza'],
            ['Asturias', 'AS', 'ES-AS', 'Oviedo'],
            ['Balearic Islands', 'IB', 'ES-IB', 'Palma'],
            ['Basque Country', 'PV', 'ES-PV', 'Vitoria-Gasteiz'],
            ['Canary Islands', 'CN', 'ES-CN', 'Las Palmas / Santa Cruz'],
            ['Cantabria', 'CB', 'ES-CB', 'Santander'],
            ['Castile and León', 'CL', 'ES-CL', 'Valladolid'],
            ['Castilla-La Mancha', 'CM', 'ES-CM', 'Toledo'],
            ['Catalonia', 'CT', 'ES-CT', 'Barcelona'],
            ['Extremadura', 'EX', 'ES-EX', 'Mérida'],
            ['Galicia', 'GA', 'ES-GA', 'Santiago de Compostela'],
            ['La Rioja', 'RI', 'ES-RI', 'Logroño'],
            ['Madrid', 'MD', 'ES-MD', 'Madrid'],
            ['Murcia', 'MC', 'ES-MC', 'Murcia'],
            ['Navarre', 'NC', 'ES-NC', 'Pamplona'],
            ['Valencia', 'VC', 'ES-VC', 'Valencia'],
        ],
        'CN' => [
            ['Anhui', 'AH', 'CN-AH', 'Hefei'],
            ['Beijing', 'BJ', 'CN-BJ', 'Beijing'],
            ['Chongqing', 'CQ', 'CN-CQ', 'Chongqing'],
            ['Fujian', 'FJ', 'CN-FJ', 'Fuzhou'],
            ['Gansu', 'GS', 'CN-GS', 'Lanzhou'],
            ['Guangdong', 'GD', 'CN-GD', 'Guangzhou'],
            ['Guangxi', 'GX', 'CN-GX', 'Nanning'],
            ['Guizhou', 'GZ', 'CN-GZ', 'Guiyang'],
            ['Hainan', 'HI', 'CN-HI', 'Haikou'],
            ['Hebei', 'HE', 'CN-HE', 'Shijiazhuang'],
            ['Heilongjiang', 'HL', 'CN-HL', 'Harbin'],
            ['Henan', 'HA', 'CN-HA', 'Zhengzhou'],
            ['Hubei', 'HB', 'CN-HB', 'Wuhan'],
            ['Hunan', 'HN', 'CN-HN', 'Changsha'],
            ['Inner Mongolia', 'NM', 'CN-NM', 'Hohhot'],
            ['Jiangsu', 'JS', 'CN-JS', 'Nanjing'],
            ['Jiangxi', 'JX', 'CN-JX', 'Nanchang'],
            ['Jilin', 'JL', 'CN-JL', 'Changchun'],
            ['Liaoning', 'LN', 'CN-LN', 'Shenyang'],
            ['Ningxia', 'NX', 'CN-NX', 'Yinchuan'],
            ['Qinghai', 'QH', 'CN-QH', 'Xining'],
            ['Shaanxi', 'SN', 'CN-SN', "Xi'an"],
            ['Shandong', 'SD', 'CN-SD', 'Jinan'],
            ['Shanghai', 'SH', 'CN-SH', 'Shanghai'],
            ['Shanxi', 'SX', 'CN-SX', 'Taiyuan'],
            ['Sichuan', 'SC', 'CN-SC', 'Chengdu'],
            ['Tianjin', 'TJ', 'CN-TJ', 'Tianjin'],
            ['Tibet', 'XZ', 'CN-XZ', 'Lhasa'],
            ['Xinjiang', 'XJ', 'CN-XJ', 'Ürümqi'],
            ['Yunnan', 'YN', 'CN-YN', 'Kunming'],
            ['Zhejiang', 'ZJ', 'CN-ZJ', 'Hangzhou'],
        ],
        'JP' => [
            ['Hokkaido', 'HKD', 'JP-01', 'Sapporo'],
            ['Aomori', 'AOM', 'JP-02', 'Aomori'],
            ['Iwate', 'IWT', 'JP-03', 'Morioka'],
            ['Miyagi', 'MYG', 'JP-04', 'Sendai'],
            ['Akita', 'AKT', 'JP-05', 'Akita'],
            ['Yamagata', 'YGT', 'JP-06', 'Yamagata'],
            ['Fukushima', 'FKS', 'JP-07', 'Fukushima'],
            ['Ibaraki', 'IBR', 'JP-08', 'Mito'],
            ['Tochigi', 'TCG', 'JP-09', 'Utsunomiya'],
            ['Gunma', 'GNM', 'JP-10', 'Maebashi'],
            ['Saitama', 'STM', 'JP-11', 'Saitama'],
            ['Chiba', 'CHB', 'JP-12', 'Chiba'],
            ['Tokyo', 'TKY', 'JP-13', 'Tokyo'],
            ['Kanagawa', 'KNG', 'JP-14', 'Yokohama'],
            ['Osaka', 'OSK', 'JP-27', 'Osaka'],
            ['Kyoto', 'KYT', 'JP-26', 'Kyoto'],
            ['Hyogo', 'HYG', 'JP-28', 'Kobe'],
            ['Aichi', 'AIC', 'JP-23', 'Nagoya'],
            ['Fukuoka', 'FKO', 'JP-40', 'Fukuoka'],
            ['Hokkaido-Okinawa', 'OKN', 'JP-47', 'Naha'],
        ],
        'BR' => [
            ['Acre', 'AC', 'BR-AC', 'Rio Branco'],
            ['Alagoas', 'AL', 'BR-AL', 'Maceió'],
            ['Amapá', 'AP', 'BR-AP', 'Macapá'],
            ['Amazonas', 'AM', 'BR-AM', 'Manaus'],
            ['Bahia', 'BA', 'BR-BA', 'Salvador'],
            ['Ceará', 'CE', 'BR-CE', 'Fortaleza'],
            ['Distrito Federal', 'DF', 'BR-DF', 'Brasília'],
            ['Espírito Santo', 'ES', 'BR-ES', 'Vitória'],
            ['Goiás', 'GO', 'BR-GO', 'Goiânia'],
            ['Maranhão', 'MA', 'BR-MA', 'São Luís'],
            ['Mato Grosso', 'MT', 'BR-MT', 'Cuiabá'],
            ['Mato Grosso do Sul', 'MS', 'BR-MS', 'Campo Grande'],
            ['Minas Gerais', 'MG', 'BR-MG', 'Belo Horizonte'],
            ['Pará', 'PA', 'BR-PA', 'Belém'],
            ['Paraíba', 'PB', 'BR-PB', 'João Pessoa'],
            ['Paraná', 'PR', 'BR-PR', 'Curitiba'],
            ['Pernambuco', 'PE', 'BR-PE', 'Recife'],
            ['Piauí', 'PI', 'BR-PI', 'Teresina'],
            ['Rio de Janeiro', 'RJ', 'BR-RJ', 'Rio de Janeiro'],
            ['Rio Grande do Norte', 'RN', 'BR-RN', 'Natal'],
            ['Rio Grande do Sul', 'RS', 'BR-RS', 'Porto Alegre'],
            ['Rondônia', 'RO', 'BR-RO', 'Porto Velho'],
            ['Roraima', 'RR', 'BR-RR', 'Boa Vista'],
            ['Santa Catarina', 'SC', 'BR-SC', 'Florianópolis'],
            ['São Paulo', 'SP', 'BR-SP', 'São Paulo'],
            ['Sergipe', 'SE', 'BR-SE', 'Aracaju'],
            ['Tocantins', 'TO', 'BR-TO', 'Palmas'],
        ],
        'MX' => [
            ['Aguascalientes', 'AGU', 'MX-AGU', 'Aguascalientes'],
            ['Baja California', 'BCN', 'MX-BCN', 'Mexicali'],
            ['Baja California Sur', 'BCS', 'MX-BCS', 'La Paz'],
            ['Campeche', 'CAM', 'MX-CAM', 'Campeche'],
            ['Chiapas', 'CHP', 'MX-CHP', 'Tuxtla Gutiérrez'],
            ['Chihuahua', 'CHH', 'MX-CHH', 'Chihuahua'],
            ['Coahuila', 'COA', 'MX-COA', 'Saltillo'],
            ['Colima', 'COL', 'MX-COL', 'Colima'],
            ['Durango', 'DUR', 'MX-DUR', 'Durango'],
            ['Guanajuato', 'GUA', 'MX-GUA', 'Guanajuato'],
            ['Guerrero', 'GRO', 'MX-GRO', 'Chilpancingo'],
            ['Hidalgo', 'HID', 'MX-HID', 'Pachuca'],
            ['Jalisco', 'JAL', 'MX-JAL', 'Guadalajara'],
            ['Mexico City', 'CMX', 'MX-CMX', 'Mexico City'],
            ['México State', 'MEX', 'MX-MEX', 'Toluca'],
            ['Michoacán', 'MIC', 'MX-MIC', 'Morelia'],
            ['Morelos', 'MOR', 'MX-MOR', 'Cuernavaca'],
            ['Nayarit', 'NAY', 'MX-NAY', 'Tepic'],
            ['Nuevo León', 'NLE', 'MX-NLE', 'Monterrey'],
            ['Oaxaca', 'OAX', 'MX-OAX', 'Oaxaca City'],
            ['Puebla', 'PUE', 'MX-PUE', 'Puebla'],
            ['Querétaro', 'QUE', 'MX-QUE', 'Querétaro'],
            ['Quintana Roo', 'ROO', 'MX-ROO', 'Chetumal'],
            ['San Luis Potosí', 'SLP', 'MX-SLP', 'San Luis Potosí'],
            ['Sinaloa', 'SIN', 'MX-SIN', 'Culiacán'],
            ['Sonora', 'SON', 'MX-SON', 'Hermosillo'],
            ['Tabasco', 'TAB', 'MX-TAB', 'Villahermosa'],
            ['Tamaulipas', 'TAM', 'MX-TAM', 'Ciudad Victoria'],
            ['Tlaxcala', 'TLA', 'MX-TLA', 'Tlaxcala'],
            ['Veracruz', 'VER', 'MX-VER', 'Xalapa'],
            ['Yucatán', 'YUC', 'MX-YUC', 'Mérida'],
            ['Zacatecas', 'ZAC', 'MX-ZAC', 'Zacatecas'],
        ],
        'NG' => [
            ['Abia', 'AB', 'NG-AB', 'Umuahia'],
            ['Adamawa', 'AD', 'NG-AD', 'Yola'],
            ['Akwa Ibom', 'AK', 'NG-AK', 'Uyo'],
            ['Anambra', 'AN', 'NG-AN', 'Awka'],
            ['Bauchi', 'BA', 'NG-BA', 'Bauchi'],
            ['Bayelsa', 'BY', 'NG-BY', 'Yenagoa'],
            ['Benue', 'BE', 'NG-BE', 'Makurdi'],
            ['Borno', 'BO', 'NG-BO', 'Maiduguri'],
            ['Cross River', 'CR', 'NG-CR', 'Calabar'],
            ['Delta', 'DE', 'NG-DE', 'Asaba'],
            ['Ebonyi', 'EB', 'NG-EB', 'Abakaliki'],
            ['Edo', 'ED', 'NG-ED', 'Benin City'],
            ['Ekiti', 'EK', 'NG-EK', 'Ado Ekiti'],
            ['Enugu', 'EN', 'NG-EN', 'Enugu'],
            ['Federal Capital Territory', 'FC', 'NG-FC', 'Abuja'],
            ['Gombe', 'GO', 'NG-GO', 'Gombe'],
            ['Imo', 'IM', 'NG-IM', 'Owerri'],
            ['Jigawa', 'JI', 'NG-JI', 'Dutse'],
            ['Kaduna', 'KD', 'NG-KD', 'Kaduna'],
            ['Kano', 'KN', 'NG-KN', 'Kano'],
            ['Katsina', 'KT', 'NG-KT', 'Katsina'],
            ['Kebbi', 'KE', 'NG-KE', 'Birnin Kebbi'],
            ['Kogi', 'KO', 'NG-KO', 'Lokoja'],
            ['Kwara', 'KW', 'NG-KW', 'Ilorin'],
            ['Lagos', 'LA', 'NG-LA', 'Ikeja'],
            ['Nasarawa', 'NA', 'NG-NA', 'Lafia'],
            ['Niger', 'NI', 'NG-NI', 'Minna'],
            ['Ogun', 'OG', 'NG-OG', 'Abeokuta'],
            ['Ondo', 'ON', 'NG-ON', 'Akure'],
            ['Osun', 'OS', 'NG-OS', 'Osogbo'],
            ['Oyo', 'OY', 'NG-OY', 'Ibadan'],
            ['Plateau', 'PL', 'NG-PL', 'Jos'],
            ['Rivers', 'RI', 'NG-RI', 'Port Harcourt'],
            ['Sokoto', 'SO', 'NG-SO', 'Sokoto'],
            ['Taraba', 'TA', 'NG-TA', 'Jalingo'],
            ['Yobe', 'YO', 'NG-YO', 'Damaturu'],
            ['Zamfara', 'ZA', 'NG-ZA', 'Gusau'],
        ],
        'PK' => [
            ['Punjab', 'PB', 'PK-PB', 'Lahore'],
            ['Sindh', 'SD', 'PK-SD', 'Karachi'],
            ['Khyber Pakhtunkhwa', 'KP', 'PK-KP', 'Peshawar'],
            ['Balochistan', 'BA', 'PK-BA', 'Quetta'],
            ['Gilgit-Baltistan', 'GB', 'PK-GB', 'Gilgit'],
            ['Azad Kashmir', 'JK', 'PK-JK', 'Muzaffarabad'],
            ['Islamabad Capital Territory', 'IS', 'PK-IS', 'Islamabad'],
        ],
        'ZA' => [
            ['Eastern Cape', 'EC', 'ZA-EC', 'Bhisho'],
            ['Free State', 'FS', 'ZA-FS', 'Bloemfontein'],
            ['Gauteng', 'GT', 'ZA-GT', 'Johannesburg'],
            ['KwaZulu-Natal', 'NL', 'ZA-NL', 'Pietermaritzburg'],
            ['Limpopo', 'LP', 'ZA-LP', 'Polokwane'],
            ['Mpumalanga', 'MP', 'ZA-MP', 'Nelspruit'],
            ['Northern Cape', 'NC', 'ZA-NC', 'Kimberley'],
            ['North West', 'NW', 'ZA-NW', 'Mahikeng'],
            ['Western Cape', 'WC', 'ZA-WC', 'Cape Town'],
        ],
        'AR' => [
            ['Buenos Aires', 'BA', 'AR-B', 'La Plata'],
            ['Ciudad Autónoma de Buenos Aires', 'CABA', 'AR-C', 'Buenos Aires'],
            ['Catamarca', 'CT', 'AR-K', 'San Fernando del Valle de Catamarca'],
            ['Chaco', 'CC', 'AR-H', 'Resistencia'],
            ['Chubut', 'CH', 'AR-U', 'Rawson'],
            ['Córdoba', 'CB', 'AR-X', 'Córdoba'],
            ['Corrientes', 'CN', 'AR-W', 'Corrientes'],
            ['Entre Ríos', 'ER', 'AR-E', 'Paraná'],
            ['Formosa', 'FM', 'AR-P', 'Formosa'],
            ['Jujuy', 'JY', 'AR-Y', 'San Salvador de Jujuy'],
            ['La Pampa', 'LP', 'AR-L', 'Santa Rosa'],
            ['La Rioja', 'LR', 'AR-F', 'La Rioja'],
            ['Mendoza', 'MZ', 'AR-M', 'Mendoza'],
            ['Misiones', 'MN', 'AR-N', 'Posadas'],
            ['Neuquén', 'NQ', 'AR-Q', 'Neuquén'],
            ['Río Negro', 'RN', 'AR-R', 'Viedma'],
            ['Salta', 'SA', 'AR-A', 'Salta'],
            ['San Juan', 'SJ', 'AR-J', 'San Juan'],
            ['San Luis', 'SL', 'AR-D', 'San Luis'],
            ['Santa Cruz', 'SC', 'AR-Z', 'Río Gallegos'],
            ['Santa Fe', 'SF', 'AR-S', 'Santa Fe'],
            ['Santiago del Estero', 'SE', 'AR-G', 'Santiago del Estero'],
            ['Tierra del Fuego', 'TF', 'AR-V', 'Ushuaia'],
            ['Tucumán', 'TM', 'AR-T', 'San Miguel de Tucumán'],
        ],
        'MY' => [
            ['Johor', 'JHR', 'MY-01', 'Johor Bahru'],
            ['Kedah', 'KDH', 'MY-02', 'Alor Setar'],
            ['Kelantan', 'KTN', 'MY-03', 'Kota Bharu'],
            ['Malacca', 'MLK', 'MY-04', 'Malacca City'],
            ['Negeri Sembilan', 'NSN', 'MY-05', 'Seremban'],
            ['Pahang', 'PHG', 'MY-06', 'Kuantan'],
            ['Penang', 'PNG', 'MY-07', 'George Town'],
            ['Perak', 'PRK', 'MY-08', 'Ipoh'],
            ['Perlis', 'PLS', 'MY-09', 'Kangar'],
            ['Sabah', 'SBH', 'MY-12', 'Kota Kinabalu'],
            ['Sarawak', 'SWK', 'MY-13', 'Kuching'],
            ['Selangor', 'SGR', 'MY-10', 'Shah Alam'],
            ['Terengganu', 'TRG', 'MY-11', 'Kuala Terengganu'],
            ['Kuala Lumpur', 'KUL', 'MY-14', 'Kuala Lumpur'],
            ['Labuan', 'LBN', 'MY-15', 'Victoria'],
            ['Putrajaya', 'PJY', 'MY-16', 'Putrajaya'],
        ],
        'AE' => [
            ['Abu Dhabi', 'AZ', 'AE-AZ', 'Abu Dhabi'],
            ['Ajman', 'AJ', 'AE-AJ', 'Ajman'],
            ['Dubai', 'DU', 'AE-DU', 'Dubai'],
            ['Fujairah', 'FU', 'AE-FU', 'Fujairah'],
            ['Ras Al Khaimah', 'RK', 'AE-RK', 'Ras Al Khaimah'],
            ['Sharjah', 'SH', 'AE-SH', 'Sharjah'],
            ['Umm Al Quwain', 'UQ', 'AE-UQ', 'Umm Al Quwain'],
        ],
        'SA' => [
            ['Riyadh', 'RI', 'SA-01', 'Riyadh'],
            ['Makkah', 'MK', 'SA-02', 'Mecca'],
            ['Madinah', 'MD', 'SA-03', 'Medina'],
            ['Qassim', 'QS', 'SA-04', 'Buraidah'],
            ['Eastern Province', 'EP', 'SA-05', 'Dammam'],
            ['Asir', 'AS', 'SA-14', 'Abha'],
            ['Tabuk', 'TB', 'SA-07', 'Tabuk'],
            ['Hail', 'HA', 'SA-06', "Ha'il"],
            ['Northern Borders', 'NB', 'SA-08', 'Arar'],
            ['Jazan', 'JZ', 'SA-09', 'Jazan'],
            ['Najran', 'NJ', 'SA-10', 'Najran'],
            ['Al Bahah', 'BH', 'SA-11', 'Al Bahah'],
            ['Al Jouf', 'JF', 'SA-12', 'Sakakah'],
        ],
    ];

    public function run(): void
    {
        $countryIdsByIso2 = Country::query()->pluck('id', 'iso2');

        foreach (self::STATES_BY_ISO2 as $iso2 => $states) {
            $countryId = $countryIdsByIso2[$iso2] ?? null;

            if ($countryId === null) {
                continue;
            }

            foreach ($states as $sortOrder => [$name, $code, $isoCode, $capital]) {
                State::updateOrCreate(
                    ['country_id' => $countryId, 'code' => $code],
                    [
                        'name' => $name,
                        'iso_code' => $isoCode,
                        'capital' => $capital,
                        'sort_order' => $sortOrder,
                        'status' => 'active',
                    ]
                );
            }
        }
    }
}
