<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Filament\Resources\ActivityLog\ActivityLogResource;
use App\Filament\Resources\ActivityLog\Pages\ListActivityLogs;
use App\Filament\Resources\ActivityLog\Pages\ViewActivityLog;
use App\Models\User;
use App\Policies\ActivityLogPolicy;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Spatie\Activitylog\Models\Activity;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class ActivityLogResourceTest extends TestCase
{
    use RefreshDatabase;

    private User $superAdmin;
    private User $logViewer;
    private User $regularUser;

    protected function setUp(): void
    {
        parent::setUp();

        // Seed permissions needed by all sidebar items to avoid Spatie exceptions
        foreach (['activity_log.view', 'cache_manager.view', 'cache_manager.clear', 'cache_manager.optimize'] as $perm) {
            Permission::firstOrCreate(['name' => $perm, 'guard_name' => 'web']);
        }

        $superAdminRole = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        $this->superAdmin = User::factory()->create(['status' => 'active']);
        $this->superAdmin->assignRole($superAdminRole);

        $this->logViewer = User::factory()->create(['status' => 'active']);
        $this->logViewer->givePermissionTo('activity_log.view');

        $this->regularUser = User::factory()->create(['status' => 'active']);

        // Wipe any activity entries generated by setUp itself
        Activity::query()->delete();
    }

    // ── Access control ─────────────────────────────────────────────────────

    public function test_super_admin_can_access_activity_log_index(): void
    {
        $this->actingAs($this->superAdmin)
            ->get(ActivityLogResource::getUrl('index'))
            ->assertOk();
    }

    public function test_user_with_permission_can_access_activity_log_index(): void
    {
        $this->actingAs($this->logViewer)
            ->get(ActivityLogResource::getUrl('index'))
            ->assertOk();
    }

    public function test_regular_user_cannot_access_activity_log_index(): void
    {
        $this->actingAs($this->regularUser)
            ->get(ActivityLogResource::getUrl('index'))
            ->assertForbidden();
    }

    public function test_guest_is_redirected_from_activity_log_index(): void
    {
        $this->get(ActivityLogResource::getUrl('index'))
            ->assertRedirect();
    }

    // ── Read-only enforcement ─────────────────────────────────────────────

    public function test_canCreate_is_always_false(): void
    {
        $this->assertFalse(ActivityLogResource::canCreate());
    }

    public function test_canDeleteAny_is_always_false(): void
    {
        $this->assertFalse(ActivityLogResource::canDeleteAny());
    }

    public function test_canEdit_is_always_false(): void
    {
        $activity = $this->makeActivity();
        $this->assertFalse(ActivityLogResource::canEdit($activity));
    }

    public function test_canDelete_is_always_false(): void
    {
        $activity = $this->makeActivity();
        $this->assertFalse(ActivityLogResource::canDelete($activity));
    }

    // ── List page ─────────────────────────────────────────────────────────

    public function test_list_page_shows_activity_entries(): void
    {
        $this->makeActivity('created', 'test-channel');
        $this->makeActivity('deleted', 'test-channel');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->assertSuccessful()
            ->assertCountTableRecords(2);
    }

    public function test_list_page_can_be_searched_by_description(): void
    {
        $this->makeActivity('created', 'test', 'unique-description-xyz');
        $this->makeActivity('created', 'test', 'other-entry');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->searchTable('unique-description-xyz')
            ->assertCountTableRecords(1);
    }

    public function test_list_page_can_filter_by_event(): void
    {
        $this->makeActivity('created', 'test');
        $this->makeActivity('deleted', 'test');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('event', 'created')
            ->assertCountTableRecords(1);
    }

    public function test_list_page_can_filter_by_log_name(): void
    {
        $this->makeActivity('created', 'auth');
        $this->makeActivity('created', 'cms');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('log_name', 'auth')
            ->assertCountTableRecords(1);
    }

    public function test_list_page_can_filter_by_subject_type(): void
    {
        activity('test')->performedOn($this->superAdmin)->log('on user');
        activity('test')->log('no subject');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('subject_type', \App\Models\User::class)
            ->assertCountTableRecords(1);
    }

    // ── View page ─────────────────────────────────────────────────────────

    public function test_super_admin_can_view_activity_detail(): void
    {
        $activity = $this->makeActivity();

        $this->actingAs($this->superAdmin)
            ->get(ActivityLogResource::getUrl('view', ['record' => $activity->id]))
            ->assertOk();
    }

    public function test_regular_user_cannot_view_activity_detail(): void
    {
        $activity = $this->makeActivity();

        $this->actingAs($this->regularUser)
            ->get(ActivityLogResource::getUrl('view', ['record' => $activity->id]))
            ->assertForbidden();
    }

    // ── Policy ────────────────────────────────────────────────────────────

    public function test_policy_viewAny_grants_super_admin(): void
    {
        $policy = new ActivityLogPolicy();
        $this->assertTrue($policy->viewAny($this->superAdmin));
    }

    public function test_policy_viewAny_grants_user_with_permission(): void
    {
        $policy = new ActivityLogPolicy();
        $this->assertTrue($policy->viewAny($this->logViewer));
    }

    public function test_policy_viewAny_denies_regular_user(): void
    {
        $policy = new ActivityLogPolicy();
        $this->assertFalse($policy->viewAny($this->regularUser));
    }

    public function test_policy_view_mirrors_viewAny(): void
    {
        $policy = new ActivityLogPolicy();
        $this->assertTrue($policy->view($this->superAdmin));
        $this->assertFalse($policy->view($this->regularUser));
    }

    public function test_policy_denies_when_permission_does_not_exist(): void
    {
        // Create a user with no role/permission and no 'activity_log.view' permission seeded
        Permission::where('name', 'activity_log.view')->delete();

        $policy = new ActivityLogPolicy();
        $this->assertFalse($policy->viewAny($this->regularUser));
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private function makeActivity(
        string $event = 'created',
        string $logName = 'test',
        string $description = 'Test activity entry',
    ): Activity {
        return activity($logName)
            ->causedBy($this->superAdmin)
            ->event($event)
            ->withProperties(['ip' => '127.0.0.1', 'user_agent' => 'PHPUnit/Test'])
            ->log($description);
    }
}
