<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Filament\Resources\ActivityLog\ActivityLogResource;
use App\Filament\Resources\ActivityLog\Pages\ListActivityLogs;
use App\Models\Country;
use App\Models\Page;
use App\Models\User;
use App\Policies\ActivityLogPolicy;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Livewire\Livewire;
use Spatie\Activitylog\Models\Activity;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Tests\TestCase;

class ActivityLogResourceTest extends TestCase
{
    use RefreshDatabase;

    private User $superAdmin;

    private User $logViewer;

    private User $regularUser;

    protected function setUp(): void
    {
        parent::setUp();

        // Seed permissions needed by all sidebar items to avoid Spatie exceptions
        foreach (['activity_log.view', 'cache_manager.view', 'cache_manager.clear', 'cache_manager.optimize'] as $perm) {
            Permission::firstOrCreate(['name' => $perm, 'guard_name' => 'web']);
        }

        $superAdminRole = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        $this->superAdmin = User::factory()->create(['status' => 'active']);
        $this->superAdmin->assignRole($superAdminRole);

        $this->logViewer = User::factory()->create(['status' => 'active']);
        $this->logViewer->givePermissionTo('activity_log.view');

        $this->regularUser = User::factory()->create(['status' => 'active']);

        // Wipe any activity entries generated by setUp itself
        Activity::query()->delete();
    }

    // ── Access control ─────────────────────────────────────────────────────

    public function test_super_admin_can_access_activity_log_index(): void
    {
        $this->actingAs($this->superAdmin)
            ->get(ActivityLogResource::getUrl('index'))
            ->assertOk();
    }

    public function test_user_with_permission_can_access_activity_log_index(): void
    {
        $this->actingAs($this->logViewer)
            ->get(ActivityLogResource::getUrl('index'))
            ->assertOk();
    }

    public function test_regular_user_cannot_access_activity_log_index(): void
    {
        $this->actingAs($this->regularUser)
            ->get(ActivityLogResource::getUrl('index'))
            ->assertForbidden();
    }

    public function test_guest_is_redirected_from_activity_log_index(): void
    {
        $this->get(ActivityLogResource::getUrl('index'))
            ->assertRedirect();
    }

    // ── Read-only enforcement ─────────────────────────────────────────────

    public function test_can_create_is_always_false(): void
    {
        $this->assertFalse(ActivityLogResource::canCreate());
    }

    public function test_can_delete_any_is_always_false(): void
    {
        $this->assertFalse(ActivityLogResource::canDeleteAny());
    }

    public function test_can_edit_is_always_false(): void
    {
        $activity = $this->makeActivity();
        $this->assertFalse(ActivityLogResource::canEdit($activity));
    }

    public function test_can_delete_is_always_false(): void
    {
        $activity = $this->makeActivity();
        $this->assertFalse(ActivityLogResource::canDelete($activity));
    }

    // ── List page ─────────────────────────────────────────────────────────

    public function test_list_page_shows_activity_entries(): void
    {
        $this->makeActivity('created', 'test-channel');
        $this->makeActivity('deleted', 'test-channel');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->assertSuccessful()
            ->assertCountTableRecords(2);
    }

    public function test_list_page_can_be_searched_by_description(): void
    {
        $this->makeActivity('created', 'test', 'unique-description-xyz');
        $this->makeActivity('created', 'test', 'other-entry');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->searchTable('unique-description-xyz')
            ->assertCountTableRecords(1);
    }

    public function test_list_page_can_filter_by_event(): void
    {
        $this->makeActivity('created', 'test');
        $this->makeActivity('deleted', 'test');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('event', 'created')
            ->assertCountTableRecords(1);
    }

    public function test_list_page_can_filter_by_log_name(): void
    {
        $this->makeActivity('created', 'auth');
        $this->makeActivity('created', 'cms');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('log_name', 'auth')
            ->assertCountTableRecords(1);
    }

    public function test_list_page_can_filter_by_subject_type(): void
    {
        activity('test')->performedOn($this->superAdmin)->log('on user');
        activity('test')->log('no subject');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('subject_type', User::class)
            ->assertCountTableRecords(1);
    }

    // ── View page ─────────────────────────────────────────────────────────

    public function test_super_admin_can_view_activity_detail(): void
    {
        $activity = $this->makeActivity();

        $this->actingAs($this->superAdmin)
            ->get(ActivityLogResource::getUrl('view', ['record' => $activity->id]))
            ->assertOk();
    }

    public function test_regular_user_cannot_view_activity_detail(): void
    {
        $activity = $this->makeActivity();

        $this->actingAs($this->regularUser)
            ->get(ActivityLogResource::getUrl('view', ['record' => $activity->id]))
            ->assertForbidden();
    }

    // ── Policy ────────────────────────────────────────────────────────────

    public function test_policy_view_any_grants_super_admin(): void
    {
        $policy = new ActivityLogPolicy;
        $this->assertTrue($policy->viewAny($this->superAdmin));
    }

    public function test_policy_view_any_grants_user_with_permission(): void
    {
        $policy = new ActivityLogPolicy;
        $this->assertTrue($policy->viewAny($this->logViewer));
    }

    public function test_policy_view_any_denies_regular_user(): void
    {
        $policy = new ActivityLogPolicy;
        $this->assertFalse($policy->viewAny($this->regularUser));
    }

    public function test_policy_view_mirrors_view_any(): void
    {
        $policy = new ActivityLogPolicy;
        $this->assertTrue($policy->view($this->superAdmin));
        $this->assertFalse($policy->view($this->regularUser));
    }

    public function test_policy_denies_when_permission_does_not_exist(): void
    {
        // Create a user with no role/permission and no 'activity_log.view' permission seeded
        Permission::where('name', 'activity_log.view')->delete();

        $policy = new ActivityLogPolicy;
        $this->assertFalse($policy->viewAny($this->regularUser));
    }

    // ── Filter: causer_id ─────────────────────────────────────────────────

    public function test_list_page_can_filter_by_causer_id(): void
    {
        activity('test')->causedBy($this->superAdmin)->log('by super admin');
        activity('test')->causedBy($this->logViewer)->log('by log viewer');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('causer_id', $this->superAdmin->id)
            ->assertCountTableRecords(1);
    }

    // ── Filter: date range ────────────────────────────────────────────────

    public function test_list_page_can_filter_by_date_range(): void
    {
        // Create one old and one recent activity
        $oldActivity = activity('test')->log('old entry');
        $oldActivity->forceFill(['created_at' => now()->subDays(10)])->saveQuietly();

        activity('test')->log('new entry');

        $this->actingAs($this->superAdmin);

        Livewire::test(ListActivityLogs::class)
            ->filterTable('date_range', [
                'from' => now()->subDays(1)->toDateString(),
                'until' => now()->toDateString(),
            ])
            ->assertCountTableRecords(1);
    }

    // ── No bulk actions ───────────────────────────────────────────────────

    public function test_list_page_has_no_bulk_actions(): void
    {
        $this->actingAs($this->superAdmin);

        // The resource disables all bulk actions — verify no delete/restore bulk action exists.
        Livewire::test(ListActivityLogs::class)
            ->assertSuccessful()
            ->assertTableBulkActionDoesNotExist('delete')
            ->assertTableBulkActionDoesNotExist('forceDelete');
    }

    // ── End-to-end: model mutation → log entry ────────────────────────────

    public function test_page_model_mutation_creates_activity_log_entry(): void
    {
        $page = Page::factory()->create(['title' => 'Original Title', 'status' => 'draft']);
        Activity::query()->delete(); // clear factory-generated activity

        $page->update(['title' => 'Updated Title']);

        // subject_type is stored via morph map (e.g. 'page'), so match on log_name and event.
        $this->assertDatabaseHas('activity_log', [
            'log_name' => 'pages',
            'event' => 'updated',
        ]);
    }

    public function test_country_model_mutation_uses_countries_log_name(): void
    {
        $country = Country::create([
            'name' => 'Test Country',
            'iso2' => 'TC',
            'iso3' => 'TCY',
            'phone_code' => '999',
            'nationality' => 'Testian',
            'status' => 'active',
        ]);
        Activity::query()->delete();

        $country->update(['name' => 'Updated Country']);

        $this->assertDatabaseHas('activity_log', [
            'log_name' => 'countries',
            'event' => 'updated',
        ]);
    }

    // ── Infolist renders ──────────────────────────────────────────────────

    public function test_view_page_renders_before_and_after_tabs(): void
    {
        $activity = activity('test')
            ->causedBy($this->superAdmin)
            ->event('updated')
            ->withProperties([
                'ip' => '127.0.0.1',
                'user_agent' => 'PHPUnit/Test',
            ])
            ->log('Test with attribute changes');

        // Manually set attribute_changes to simulate model diff
        $activity->forceFill([
            'attribute_changes' => [
                'old' => ['name' => 'Old'],
                'attributes' => ['name' => 'New'],
            ],
        ])->saveQuietly();

        $this->actingAs($this->superAdmin)
            ->get(ActivityLogResource::getUrl('view', ['record' => $activity->id]))
            ->assertOk()
            ->assertSee('Before')
            ->assertSee('After')
            ->assertSee('Metadata');
    }

    // ── Role activity logging ─────────────────────────────────────────────

    public function test_role_creation_is_logged_to_roles_channel(): void
    {
        Role::create(['name' => 'test-audited-role', 'guard_name' => 'web']);

        // Simulate what CreateRole::afterCreate() does
        activity('roles')
            ->causedBy($this->superAdmin)
            ->event('created')
            ->withProperties(['permissions_count' => 0])
            ->log('Role created');

        $this->assertDatabaseHas('activity_log', [
            'log_name' => 'roles',
            'event' => 'created',
        ]);
    }

    // ── Helpers ───────────────────────────────────────────────────────────

    private function makeActivity(
        string $event = 'created',
        string $logName = 'test',
        string $description = 'Test activity entry',
    ): Activity {
        return activity($logName)
            ->causedBy($this->superAdmin)
            ->event($event)
            ->withProperties(['ip' => '127.0.0.1', 'user_agent' => 'PHPUnit/Test'])
            ->log($description);
    }
}
